config/routes.rb
Rails.application.routes.draw do
  
  root 'rooms#home'
  get '/home', to: 'rooms#home'
  resources :rooms
  
  get '/signup', to: 'users#new'
  resources :users, except: [:index, :show] do
    member do
      get 'account'
      get 'profile'
      get 'posts'
    end
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :reservations, only: [:index, :new, :create, :destroy]
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :number, presence: true
  
  
  # 予約した日数×人数を返す (indexで使用)
  def pre_price
    (self.end.to_date - self.start.to_date).to_i * self.number.to_i
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_many :reserve_users, through: :reservations, source: :user
  validates :user_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :reservations
  has_many :reserve_rooms, through: :reservations, source: :room
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :set_q
  
  def set_q
    @q = Room.ransack(params[:q])
  end
  
  private
  
    # ユーザーのログインを確認する
    def logged_in_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create, :destroy]
  before_action :correct_user, only: [:destroy]
  
  
  def index
  end
  
  def new
    @reservation = current_user.reservations.build
    @day = (params[:end].to_date - params[:start].to_date).to_i
    @price = @day * params[:price].to_i * params[:number].to_i
  end
  
  def create
    @reservation = current_user.reservations.build(reservation_params)
    if @reservation.save
      flash[:success] = "部屋を予約しました"
      redirect_to reservations_path
    else
      render "new"
    end
  end
  
  def destroy
    @reservation.destroy
    flash[:success] = "予約をキャンセルしました"
    redirect_to reservations_path
  end
  
  
  
  private
  
    def reservation_params
      params.require(:reservation).permit(:room_id, :start, :end, :number)
    end
    
    
    # beforeアクション
    
    # 予約者かどうか確認
    def correct_user
      @reservation = current_user.reservations.find_by(id: params[:id])
      redirect_to home_url if @reservation.nil?
    end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def home
  end
  
  def new
    @room = current_user.rooms.build
  end
  
  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:success] = "新しい部屋を登録しました"
      redirect_to posts_user_url(current_user)
    else
      render "new"
    end
  end
  
  def edit
  end
  
  def update
    if @room.update(room_params)
      flash[:success] = "更新しました"
      redirect_to posts_user_url(current_user)
    else
      render 'edit'
    end
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def index
    @rooms = @q.result
  end
  
  def destroy
    @room.destroy
    flash[:success] = "削除しました"
    redirect_to posts_user_url(current_user)
  end
  
  
  
  private
  
    def room_params
      params.require(:room).permit(:name, :introduction, :price, :address, :image)
    end
    
    
    
    
    # beforeアクション
    
    # room登録者かどうか確認
    def correct_user
      @room = current_user.rooms.find_by(id: params[:id])
      redirect_to home_url if @room.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user)
      redirect_to home_path
    else
      flash.now[:danger] = "メールアドレスまたはパスワードが間違っています"
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :account, :profile, :posts]
  before_action :correct_user, only: [:edit, :update, :account, :profile, :posts]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "新しいアカウントが作成されました"
      redirect_to home_url
    else
      render "new"
    end
  end
  
  def account
  end
  
  def profile
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "アカウントを更新しました"
      redirect_to account_user_url(@user)
    else
      render 'edit'
    end
  end
  
  def destroy
  end

  def posts
  end

  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :introduction)
    end
    
    
    # beforeアクション
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to home_url unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # userでログインする
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # ログイン中のユーザーを返す
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrueを返す
  def logged_in?
    !current_user.nil?
  end
  
  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # 渡されたユーザーがcurrentユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container-fluid d-sm-flex justify-content-between">
        <div class="header-leftside d-lg-flex align-items-center">
          <%= link_to image_tag('potepan-share.png', alt:"サイトロゴ"), home_path %>
          <div class="d-flex d-lg-block d-none">
          <%= search_form_for @q, url: rooms_path do |f| %>
            <div class="search-box me-2">
              <i class="fas fa-map-marker-alt"></i>
              <%= f.search_field :address_cont, placeholder: "エリア", class: "form-control" %>
            </div>
            <div class="search-box me-2">
              <i class="fas fa-search"></i>
              <%= f.search_field :name_or_address_or_introduction_or_price_cont, placeholder: "キーワード", class: "form-control" %>
            </div>
            <%= f.submit '検索', class: "btn btn-light" %>
          <% end %>
          </div>
        </div>
        <div class="header-rightside d-flex align-items-center">
          <% if logged_in? %>
            <div class="dropdown d-flex align-items-center">
              <div class="user-name">
                <%= current_user.name %>
              </div>
              <div class="dropdown-toggle" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.avatar? %>
                  <%= image_tag(current_user.avatar.url, class: "avatar-s") %>
                <% else %>
                  <%= image_tag 'nc209714.jpeg', class: "avatar-s" %>
                <% end %>
              </div>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
                <li><%= link_to "ルーム登録", new_room_path, class: "dropdown-item" %></li>
                <li><%= link_to "予約済みルーム一覧", reservations_path, class: "dropdown-item" %></li>
                <li><%= link_to "登録済みルーム一覧", posts_user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "設定", account_user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </div>
          <% else %>
            <div class="d-flex align-items-center">
              <%= link_to "ログイン", login_path, class: "btn btn-primary me-4" %>
              <%= link_to "登録する", signup_path, class: "btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <main>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <p>©︎ 2021 POTEPAN.INC.</p>
    </footer>
  
  </body>
</html>

app/views/reservations/index.html.erb
<div class="container-fluid">
  <div class="reservations">
    <h4 class="mb-4">予約済みルーム一覧 (<%= current_user.reservations.count %>件)</h4>
    <div class="table-responsive">
      <table class="table table-hover align-middle text-center">
        <thead>
          <tr>
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>合計料金</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>予約確定日時</th>
            <th>キャンセル</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.reservations.each do |reservation| %>
          <tr>
            <td><%= link_to (image_tag reservation.room.image.thumb.url), room_path(reservation.room) %></td>
            <td class="fw-bold"><%= link_to reservation.room.name, room_path(reservation.room) %></td>
            <td><%= reservation.room.introduction %></td>
            <td>¥ <%= reservation.pre_price * reservation.room.price %></td>
            <td><%= reservation.start %></td>
            <td><%= reservation.end %></td>
            <td><%= reservation.created_at %></td>
            <td><%= link_to "キャンセル", reservation_path(reservation), method: :delete, data: { confirm: "本当にキャンセルしますか？" } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container-fluid">
  <div class="reservation-box">
    <h4 class="mb-3 border-bottom pb-3">予約内容確認</h4>
    <p>¥ <%= params[:price] %>/日</p>
    <%= form_with(model: @reservation, local: true) do |f| %>
      <%= render 'shared/error_messages', obj: @reservation %>
      <%= f.hidden_field :room_id, :value => params[:room_id] %>
      <div class="py-2 border-top">
        <%= f.label :start, "開始日" %>
        <%= f.date_field :start, value: params[:start], readonly: true, class: "form-control" %>
      </div>
      <div class="py-2">
        <%= f.label :end, "終了日" %>
        <%= f.date_field :end, value: params[:end], readonly: true, class: "form-control" %>
      </div>
      <div class="py-2">
        <p class="mb-1">使用日数</p>
        <p><%= @day %> 日</p>
      </div>
      <div class="py-2 border-top border-bottom mb-4">
        <%= f.label :number, "人数" %>
        <%= f.number_field :number, value: params[:number], readonly: true, class: "form-control" %>
      </div>
      <div class="py-2">
        <h5>合計金額</h5>
        <h4>¥ <%= @price %></h4>
        <p>上記内容でよろしければ「予約を確定」を押してください</p>
      </div>
      <div><%= f.submit "予約を確定", class: "btn btn-primary mb-3 w-100" %></div>
      <div><%= link_to "ルーム詳細に戻る", room_path(params[:room_id]), class: "btn btn-secondary w-100" %></div>
    <% end %>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- サイドバー -->
    <div class="col-lg-2 p-3">
      <ul class="nav flex-column mb-auto text-center">
        <li class="nav-item border-end border-primary border-3 nav-link"><%= link_to "基本情報", edit_room_path(@room), class: "nav-link" %></li>
      </ul>
    </div>
    <!-- メイン -->
    <div class="col-lg-10 bg-light p-5">
      <div class="flex-column bg-white border p-3">
        <%= form_with(model: @room, local: true) do |f| %>
          <%= render 'shared/error_messages', obj: @room %>
          <div class="row p-2">
            <h4>ルーム情報編集</h4>
          </div>
          <div class="row p-4 mx-2 border-top border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :name, "ルーム名" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.text_field :name, class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :introduction, "ルーム紹介" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.text_area :introduction, class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :price, "料金" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.number_field :price, class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :address, "住所" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.text_field :address, class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom justify-content-center">
            <div class="text-center"><%= image_tag @room.image.thumb.url %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :image, "ルーム画像" %></h6>
            <div class="col-md-9"><%= f.file_field :image, class: "form-control" %></div>
          </div>
          <div class="row p-4">
            <div class="mb-3"><%= f.submit "更新", class: "btn btn-primary col-md-2" %></div>
            <div><%= link_to "戻る", posts_user_path(current_user) %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/home.html.erb
<div class="top">
  <div class="container">
    <div class="row col-lg-6">
      <div class="top-column">
        <div class="top-box d-flex flex-column">
          <h2 class="mb-4">Potepan Shareでまだ体験したことのない旅をしよう</h2>
          <%= search_form_for @q, url: rooms_path do |f| %>
          <%= f.label :address_cont, "エリア" %>
          <%= f.search_field :address_cont, placeholder: "東京", class: "form-control mb-4" %>
          <%= f.submit '探す', class: "btn btn-primary w-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="recommend-area">
    <h3 class="mb-4">おすすめのエリア</h3>
    <div class="row">
      <div class="panel col-lg-3 col-6 mb-4">
        <%= link_to image_tag('img_tokyo.jpeg', class: "panel-image"), rooms_path(q: { address_cont: "東京" }) %>
        <p>東京</p>
      </div>
      <div class="panel col-lg-3 col-6 mb-4">
        <%= link_to image_tag('img_osaka.jpeg', class: "panel-image"), rooms_path(q: { address_cont: "大阪" }) %>
        <p>大阪</p>
      </div>
      <div class="panel col-lg-3 col-6 mb-4">
        <%= link_to image_tag('img_kyoto.jpeg', class: "panel-image"), rooms_path(q: { address_cont: "京都" }) %>
        <p>京都</p>
      </div>
      <div class="panel col-lg-3 col-6 mb-4">
        <%= link_to image_tag('img_sapporo.jpeg', class: "panel-image"), rooms_path(q: { address_cont: "札幌" }) %>
        <p>札幌</p>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container-fluid">
  <div class="rooms">
    <h4 class="mb-4">検索結果: <%= @rooms.count %> 件 </h4>
    <div class="row">
      <% @rooms.each do |room| %>
      <div class="col-sm-6 col-lg-4 col-xl-3 mb-3">
        <div class="room-inner">
          <%= link_to(room_path(room)) do %>
            <div><%= image_tag(room.image.thumb.url, class: "room-img") %></div>
            <div class="room-info">
              <p><%= room.name %></p>
              <p><%= room.address %></p>
              <p>¥ <%= room.price %></p>
            </div>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- サイドバー -->
    <div class="col-lg-2 p-3">
      <ul class="nav flex-column mb-auto text-center">
        <li class="nav-item border-end border-primary border-3"><%= link_to "基本情報", new_room_path, class: "nav-link" %></li>
      </ul>
    </div>
    <!-- メイン -->
    <div class="col-lg-10 bg-light p-5">
      <div class="flex-column bg-white border p-3">
        <%= form_with(model: @room, local: true) do |f| %>
          <%= render 'shared/error_messages', obj: @room %>
          <div class="row p-2">
            <h4>ルーム情報登録</h4>
          </div>
          <div class="row p-4 mx-2 border-top border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :name, "ルーム名" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.text_field :name, placeholder: "ルーム名を入力", class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :introduction, "ルーム紹介" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.text_area :introduction, placeholder: "ルームの説明を入力", class: "form-control", rows: "5" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :price, "料金" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.number_field :price, placeholder: "一日あたりの料金を入力", class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :address, "住所" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.text_field :address, placeholder: "住所を入力", class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :image, "ルーム画像" %><span class="badge bg-danger ms-1">必須</span></h6>
            <div class="col-md-9"><%= f.file_field :image, class: "form-control" %></div>
          </div>
          <div class="row p-4">
            <div><%= f.submit "登録", class: "btn btn-primary col-md-2" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row">
    <!-- 左側 -->
    <div class="col-md-8 p-3">
      <div class="room-box">
        <%= image_tag(@room.image.url, class: "room-img-bg mb-3") %>
        <div class="row mx-2 p-3 border-top border-bottom">
          <div class="col-2 text-center">
            <% if @room.user.avatar? %>
              <%= image_tag @room.user.avatar.thumb.url %>
            <% else %>
              <%= image_tag 'nc209714.jpeg', class: "avatar-s" %>
            <% end %>
          </div>
          <div class="col-10">
            <p class="fw-bold fs-5"><%= @room.name %></p>
            <p><%= @room.address %></p>
          </div>
        </div>
        <div class="row mx-2 p-3 border-bottom mb-3">
          <p><%= @room.introduction %></p>
        </div>
      </div>
    </div>
    <!-- 右側 -->
    <div class="col-md-4 p-3">
      <div class="flex-column border p-3">
        <h4 class="mb-3">ルーム予約</h4>
        <h5 class="mb-4">¥ <%= @room.price %>/日</h5>
        <%= form_with(url: new_reservation_path, method: :get, local: true) do |f| %>
        <%= hidden_field_tag :room_id, @room.id %>
        <%= hidden_field_tag :price, @room.price %>
        <h6><%= f.label :start, "開始日" %></h6>
        <div class="mb-4"><%= f.date_field :start, class: "form-control" %></div>
        <h6><%= f.label :end, "終了日" %></h6>
        <div class="mb-4"><%= f.date_field :end, class: "form-control" %></div>
        <h6><%= f.label :number, "人数" %></h6>
        <div class="mb-4"><%= f.number_field :number, class: "form-control" %></div>
        <div><%= f.submit "予約する", class: "btn btn-primary w-100" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul class="errors">
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/users/account.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- サイドバー -->
    <div class="col-lg-2 p-3">
      <ul class="nav flex-column mb-auto text-center">
        <li class="nav-item border-end border-primary border-3"><%= link_to "アカウント", account_user_path(current_user), class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "プロフィール", profile_user_path(current_user), class: "nav-link link-dark" %></li>
      </ul>
    </div>
    <!-- メイン -->
    <div class="col-lg-10 bg-light p-5">
      <div class="flex-column bg-white border p-3">
        <div class="row p-2">
          <h4>アカウント</h4>
        </div>
        <div class="row p-4 border-top border-bottom mx-2">
          <h6 class="col-md-3 fw-bold">メールアドレス</h6>
          <div class="col-md-9"><%= @user.email %></div>
        </div>
        <div class="row p-4 border-bottom mx-2">
          <h6 class="col-md-3 fw-bold">パスワード</h6>
          <div class="col-md-9">******</div>
        </div>
        <div class="row p-4">
          <div><%= link_to "編集", edit_user_path(current_user), class: "btn btn-primary col-md-2" %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/posts.html.erb
<div class="container-fluid">
  <div class="posts">
    <h4 class="mb-4">登録済みルーム一覧 (<%= current_user.rooms.count %>件)</h4>
    <div class="table-responsive">
      <table class="table table-hover align-middle text-center">
        <thead>
          <tr>
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>料金</th>
            <th>作成日</th>
            <th>編集</th>
            <th>削除</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.rooms.each do |room| %>
          <tr>
            <td><%= link_to (image_tag room.image.thumb.url), room_path(room) %></td>
            <td class="fw-bold"><%= link_to room.name, room_path(room) %></td>
            <td><%= room.introduction %></td>
            <td>¥ <%= room.price %></td>
            <td><%= room.created_at %></td>
            <td><%= link_to "編集", edit_room_path(room) %></td>
            <td><%= link_to "削除", room_path(room), method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- サイドバー -->
    <div class="col-lg-2 p-3">
      <ul class="nav flex-column mb-auto text-center">
        <li class="nav-item"><%= link_to "アカウント", account_user_path(current_user), class: "nav-link link-dark" %></li>
        <li class="nav-item border-end border-primary border-3"><%= link_to "プロフィール", profile_user_path(current_user), class: "nav-link" %></li>
      </ul>
    </div>
    <!-- メイン -->
    <div class="col-lg-10 bg-light p-5">
      <div class="flex-column bg-white border p-3">
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render 'shared/error_messages', obj: @user %>
          <div class="row p-2">
            <h4>プロフィール</h4>
          </div>
          <div class="row justify-content-center mx-2 py-2 border-top border-bottom">
            <div class="text-center">
              <% if @user.avatar? %>
                <%= image_tag @user.avatar.url %>
              <% else %>
                <%= image_tag 'nc209714.jpeg', class: "avatar" %>
              <% end %>
            </div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :avatar, "アイコン画像" %></h6>
            <div class="col-md-9"><%= f.file_field :avatar, class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :name, "ユーザー名" %></h6>
            <div class="col-md-9"><%= f.text_field :name, class: "form-control" %></div>
          </div>
          <div class="row p-4 mx-2 border-bottom">
            <h6 class="col-md-3 fw-bold"><%= f.label :introduction, "自己紹介" %></h6>
            <div class="col-md-9"><%= f.text_area :introduction, class: "form-control", rows: "5" %></div>
          </div>
          <div class="row p-4">
            <div><%= f.submit "更新", class: "btn btn-primary col-md-2" %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>
<ul>
  <li><%= @user.id %></li>
  <li><%= @user.name %></li>
  <li><%= @user.email %></li>
  <li><%= @user.password_digest %></li>
  <li><%= @user.image %></li>
  <li><%= @user.introduction %></li>
</ul>